# This file is auto-generated by mcp_generator.py.
# MCP server stub generated from OpenAPI spec.
import os
import json
from typing import Optional, Union, Any
from dotenv import load_dotenv
load_dotenv()
from fastmcp import FastMCP
import requests
print("[MCP SERVER] FastMCP server running.")
if __name__ == "__main__":
    mcp = FastMCP("my-server")

    @mcp.tool(name='Property_listGet', description="Get a properties list: Get the list of properties.<br>You need to be authorized (no particular scope required)")
    def Property_listGet(status: Optional[str] = None, includeArchived: Optional[bool] = None, countryCode: Optional[str] = None, pageNumber: Optional[int] = None, pageSize: Optional[int] = None, expand: Optional[str] = None):
        '''Get the list of properties.<br>You need to be authorized (no particular scope required)'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/properties"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if status is not None:
            params['status'] = status
        if includeArchived is not None:
            params['includeArchived'] = includeArchived
        if countryCode is not None:
            params['countryCode'] = countryCode
        if pageNumber is not None:
            params['pageNumber'] = pageNumber
        if pageSize is not None:
            params['pageSize'] = pageSize
        if expand is not None:
            params['expand'] = expand
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Property_create', description="Creates a property: Use this call to create a new property.<br>You must have at least one of these scopes: 'properties.create, setup.manage'.")
    def Property_create(Idempotency_Key: Optional[str] = None, body: Optional[dict] = None):
        '''Use this call to create a new property.<br>You must have at least one of these scopes: 'properties.create, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/properties"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        header_value = Idempotency_Key if Idempotency_Key is not None else os.getenv('IDEMPOTENCY_KEY')
        if header_value is not None:
            headers['Idempotency-Key'] = header_value
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Property_getTotalCount', description="Return total count of properties: Return total count of properties<br>You need to be authorized (no particular scope required)")
    def Property_getTotalCount():
        '''Return total count of properties<br>You need to be authorized (no particular scope required)'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/properties/$count"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Property_existsByIdHead', description="Check if a property exists: Check if a property exists by id.<br>You need to be authorized (no particular scope required)")
    def Property_existsByIdHead(id: str):
        '''Check if a property exists by id.<br>You need to be authorized (no particular scope required)'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/properties/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.head(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Property_getById', description="Get a property: Get a property by id.<br>You need to be authorized (no particular scope required)")
    def Property_getById(id: str, languages: Optional[str] = None, expand: Optional[str] = None):
        '''Get a property by id.<br>You need to be authorized (no particular scope required)'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/properties/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        if languages is not None:
            params['languages'] = languages
        if expand is not None:
            params['expand'] = expand
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Property_modifyDetails', description="Allows to modify property: Here's a list of allowed operations:\r\n- Replace Name\r\n- Add, replace and remove Description\r\n- Replace CompanyName\r\n- Add, replace and remove ManagingDirectors\r\n- Replace CommercialRegisterEntry\r\n- Replace TaxId\r\n- Replace Location\r\n- Add, replace and remove BankAccount\r\n- Replace PaymentTerms\r\n- Set IsTemplate<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.")
    def Property_modifyDetails(id: str, body: Optional[dict] = None):
        '''Here's a list of allowed operations:  - Replace Name  - Add, replace and remove Description  - Replace CompanyName  - Add, replace and remove ManagingDirectors  - Replace CommercialRegisterEntry  - Replace TaxId  - Replace Location  - Add, replace and remove BankAccount  - Replace PaymentTerms  - Set IsTemplate<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/properties/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.patch(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='PropertyActions_cloneProperty', description="Clones a property: Use this call to clone a specific property.\r\nThis operation creates a new property with inventory and rate plans from the specified property.<br>You must have at least one of these scopes: 'properties.create, setup.manage'.")
    def PropertyActions_cloneProperty(id: str, Idempotency_Key: Optional[str] = None, body: Optional[dict] = None):
        '''Use this call to clone a specific property.  This operation creates a new property with inventory and rate plans from the specified property.<br>You must have at least one of these scopes: 'properties.create, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/property-actions/{id}/clone"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        header_value = Idempotency_Key if Idempotency_Key is not None else os.getenv('IDEMPOTENCY_KEY')
        if header_value is not None:
            headers['Idempotency-Key'] = header_value
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='PropertyActions_archiveProperty', description="Archive a property: Use this endpoint to archive an existing live property\r\nThis operation set the IsArchived flag to true<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.")
    def PropertyActions_archiveProperty(id: str):
        '''Use this endpoint to archive an existing live property  This operation set the IsArchived flag to true<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/property-actions/{id}/archive"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.put(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='PropertyActions_moveToLive', description="Move property to live: Use this endpoint to move an existing test property to live\r\nThis operation changes the property status to 'Live'<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.")
    def PropertyActions_moveToLive(id: str):
        '''Use this endpoint to move an existing test property to live  This operation changes the property status to 'Live'<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/property-actions/{id}/set-live"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.put(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='PropertyActions_resetPropertyData', description="Reset a test property and delete all transactional data: Use this endpoint to delete all transactional data related to some test property\r\nThis operation deletes all transactional data related to the specified property. The property must be in 'Test' status.<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.")
    def PropertyActions_resetPropertyData(id: str):
        '''Use this endpoint to delete all transactional data related to some test property  This operation deletes all transactional data related to the specified property. The property must be in 'Test' status.<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/property-actions/{id}/reset"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.put(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Types_supportedCountriesList', description="Returns a list of supported countries.: Returns a list of ISO country codes that could be used to create properties.<br>You need to be authorized (no particular scope required)")
    def Types_supportedCountriesList():
        '''Returns a list of ISO country codes that could be used to create properties.<br>You need to be authorized (no particular scope required)'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/types/countries"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Unit_updateProperties', description="Allows to patch unit: Here's a list of allowed operations:\r\n- Set unit condition\r\n- Set unit description\r\n- Set unit name\r\n- Set unit unitGroupId\r\n- Set unit maxPersons\r\n- Add unit attribute\r\n- Remove unit attribute<br>You must have at least one of these scopes: 'units.manage, setup.manage'.")
    def Unit_updateProperties(id: str, body: Optional[dict] = None):
        '''Here's a list of allowed operations:  - Set unit condition  - Set unit description  - Set unit name  - Set unit unitGroupId  - Set unit maxPersons  - Add unit attribute  - Remove unit attribute<br>You must have at least one of these scopes: 'units.manage, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/units/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.patch(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Unit_getById', description="Get a unit: Get a unit by id.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.")
    def Unit_getById(id: str, languages: Optional[str] = None, expand: Optional[str] = None):
        '''Get a unit by id.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/units/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        if languages is not None:
            params['languages'] = languages
        if expand is not None:
            params['expand'] = expand
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Unit_existsByIdHead', description="Check if a unit exists: Check if a unit exists by id.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.")
    def Unit_existsByIdHead(id: str):
        '''Check if a unit exists by id.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/units/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.head(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Unit_deleteById', description="Delete a unit: Use this call to delete a unit.<br>You must have at least one of these scopes: 'units.delete, setup.manage'.")
    def Unit_deleteById(id: str):
        '''Use this call to delete a unit.<br>You must have at least one of these scopes: 'units.delete, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/units/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.delete(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Unit_updateUnitsAttributes', description="Allows to patch one or more units: Here's a list of allowed operations:\r\n- Set unit condition\r\n- Set unit description\r\n- Set unit name\r\n- Set unit unitGroupId\r\n- Set unit maxPersons\r\n- Add unit attribute\r\n- Remove unit attribute<br>You must have at least one of these scopes: 'units.manage, setup.manage'.")
    def Unit_updateUnitsAttributes(unitIds: Optional[str] = None, body: Optional[dict] = None):
        '''Here's a list of allowed operations:  - Set unit condition  - Set unit description  - Set unit name  - Set unit unitGroupId  - Set unit maxPersons  - Add unit attribute  - Remove unit attribute<br>You must have at least one of these scopes: 'units.manage, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/units"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if unitIds is not None:
            params['unitIds'] = unitIds
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.patch(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Unit_listUnits', description="Get a units list: Get the list of units.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.")
    def Unit_listUnits(propertyId: Optional[str] = None, unitGroupId: Optional[str] = None, unitGroupIds: Optional[str] = None, unitAttributeIds: Optional[str] = None, isOccupied: Optional[bool] = None, maintenanceType: Optional[str] = None, condition: Optional[str] = None, textSearch: Optional[str] = None, pageNumber: Optional[int] = None, pageSize: Optional[int] = None, expand: Optional[str] = None):
        '''Get the list of units.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/units"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if propertyId is not None:
            params['propertyId'] = propertyId
        if unitGroupId is not None:
            params['unitGroupId'] = unitGroupId
        if unitGroupIds is not None:
            params['unitGroupIds'] = unitGroupIds
        if unitAttributeIds is not None:
            params['unitAttributeIds'] = unitAttributeIds
        if isOccupied is not None:
            params['isOccupied'] = isOccupied
        if maintenanceType is not None:
            params['maintenanceType'] = maintenanceType
        if condition is not None:
            params['condition'] = condition
        if textSearch is not None:
            params['textSearch'] = textSearch
        if pageNumber is not None:
            params['pageNumber'] = pageNumber
        if pageSize is not None:
            params['pageSize'] = pageSize
        if expand is not None:
            params['expand'] = expand
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Unit_create', description="Create a unit: Use this call to create a new unit.<br>You must have at least one of these scopes: 'units.create, setup.manage'.")
    def Unit_create(Idempotency_Key: Optional[str] = None, body: Optional[dict] = None):
        '''Use this call to create a new unit.<br>You must have at least one of these scopes: 'units.create, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/units"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        header_value = Idempotency_Key if Idempotency_Key is not None else os.getenv('IDEMPOTENCY_KEY')
        if header_value is not None:
            headers['Idempotency-Key'] = header_value
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Unit_getCount', description="Returns number of units: Returns number of units matching the filter criteria<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.")
    def Unit_getCount(propertyId: Optional[str] = None, unitGroupId: Optional[str] = None, unitGroupIds: Optional[str] = None, unitAttributeIds: Optional[str] = None, isOccupied: Optional[bool] = None, maintenanceType: Optional[str] = None, condition: Optional[str] = None, textSearch: Optional[str] = None):
        '''Returns number of units matching the filter criteria<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/units/$count"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if propertyId is not None:
            params['propertyId'] = propertyId
        if unitGroupId is not None:
            params['unitGroupId'] = unitGroupId
        if unitGroupIds is not None:
            params['unitGroupIds'] = unitGroupIds
        if unitAttributeIds is not None:
            params['unitAttributeIds'] = unitAttributeIds
        if isOccupied is not None:
            params['isOccupied'] = isOccupied
        if maintenanceType is not None:
            params['maintenanceType'] = maintenanceType
        if condition is not None:
            params['condition'] = condition
        if textSearch is not None:
            params['textSearch'] = textSearch
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='Unit_bulkCreateUnits', description="Create multiple units: Use this call to create multiple units, following a naming rule.<br>You must have at least one of these scopes: 'units.create, setup.manage'.")
    def Unit_bulkCreateUnits(Idempotency_Key: Optional[str] = None, body: Optional[dict] = None):
        '''Use this call to create multiple units, following a naming rule.<br>You must have at least one of these scopes: 'units.create, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/units/bulk"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        header_value = Idempotency_Key if Idempotency_Key is not None else os.getenv('IDEMPOTENCY_KEY')
        if header_value is not None:
            headers['Idempotency-Key'] = header_value
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitAttribute_getById', description="Get unit attribute by id: Get unit attribute by id<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'.")
    def UnitAttribute_getById(id: str):
        '''Get unit attribute by id<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-attributes/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitAttribute_modifyDescription', description="Allows to modify unit attribute: Here's a list of allowed operations:\r\n- Replace / Remove Description<br>You must have at least one of these scopes: 'unitattributes.manage, setup.manage'.")
    def UnitAttribute_modifyDescription(id: str, body: Optional[dict] = None):
        '''Here's a list of allowed operations:  - Replace / Remove Description<br>You must have at least one of these scopes: 'unitattributes.manage, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-attributes/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.patch(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitAttribute_deleteById', description="Deletes unit attribute: Deletes unit attribute<br>You must have at least one of these scopes: 'unitattributes.delete, setup.manage'.")
    def UnitAttribute_deleteById(id: str):
        '''Deletes unit attribute<br>You must have at least one of these scopes: 'unitattributes.delete, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-attributes/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.delete(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitAttribute_checkExistsHead', description="Check if a unit attribute exists: Check if a unit attribute exists<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'.")
    def UnitAttribute_checkExistsHead(id: str):
        '''Check if a unit attribute exists<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-attributes/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.head(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitAttribute_listAttributes', description="Get unit attribute list: Get unit attribute list<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'.")
    def UnitAttribute_listAttributes(pageNumber: Optional[int] = None, pageSize: Optional[int] = None):
        '''Get unit attribute list<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-attributes"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if pageNumber is not None:
            params['pageNumber'] = pageNumber
        if pageSize is not None:
            params['pageSize'] = pageSize
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitAttribute_createNewAttribute', description="Create a unit attribute: Use this call to create a new unit attribute.<br>You must have at least one of these scopes: 'unitattributes.create, setup.manage'.")
    def UnitAttribute_createNewAttribute(Idempotency_Key: Optional[str] = None, body: Optional[dict] = None):
        '''Use this call to create a new unit attribute.<br>You must have at least one of these scopes: 'unitattributes.create, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-attributes"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        header_value = Idempotency_Key if Idempotency_Key is not None else os.getenv('IDEMPOTENCY_KEY')
        if header_value is not None:
            headers['Idempotency-Key'] = header_value
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitGroup_createNewGroup', description="Create a unit group: Use this call to create a new unit group.<br>You must have at least one of these scopes: 'unitgroups.create, setup.manage'.")
    def UnitGroup_createNewGroup(Idempotency_Key: Optional[str] = None, body: Optional[dict] = None):
        '''Use this call to create a new unit group.<br>You must have at least one of these scopes: 'unitgroups.create, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-groups"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        header_value = Idempotency_Key if Idempotency_Key is not None else os.getenv('IDEMPOTENCY_KEY')
        if header_value is not None:
            headers['Idempotency-Key'] = header_value
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitGroup_getAll', description="Get all unit groups, or all unit groups for a property: Get the list of unit groups.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.")
    def UnitGroup_getAll(propertyId: Optional[str] = None, unitGroupTypes: Optional[str] = None, pageNumber: Optional[int] = None, pageSize: Optional[int] = None, expand: Optional[str] = None):
        '''Get the list of unit groups.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-groups"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if propertyId is not None:
            params['propertyId'] = propertyId
        if unitGroupTypes is not None:
            params['unitGroupTypes'] = unitGroupTypes
        if pageNumber is not None:
            params['pageNumber'] = pageNumber
        if pageSize is not None:
            params['pageSize'] = pageSize
        if expand is not None:
            params['expand'] = expand
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitGroup_getCount', description="Returns number of unit groups: Returns number of unit groups matching the filter criteria<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.")
    def UnitGroup_getCount(propertyId: Optional[str] = None, unitGroupTypes: Optional[str] = None):
        '''Returns number of unit groups matching the filter criteria<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-groups/$count"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if propertyId is not None:
            params['propertyId'] = propertyId
        if unitGroupTypes is not None:
            params['unitGroupTypes'] = unitGroupTypes
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitGroup_checkExistsByIdHead', description="Check if a unit group exists: Check if a unit group exists by id.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.")
    def UnitGroup_checkExistsByIdHead(id: str):
        '''Check if a unit group exists by id.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-groups/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.head(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitGroup_getById', description="Get a unit group: Get a unit group by id.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.")
    def UnitGroup_getById(id: str, languages: Optional[str] = None, expand: Optional[str] = None):
        '''Get a unit group by id.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-groups/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        if languages is not None:
            params['languages'] = languages
        if expand is not None:
            params['expand'] = expand
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.get(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitGroup_updateGroup', description="Replace a unit group: Use this call to modify a unit group.<br>You must have at least one of these scopes: 'unitgroups.manage, setup.manage'.")
    def UnitGroup_updateGroup(id: str, body: Optional[dict] = None):
        '''Use this call to modify a unit group.<br>You must have at least one of these scopes: 'unitgroups.manage, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-groups/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.put(url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='UnitGroup_deleteById', description="Delete a unit group: Use this call to delete a unit group.<br>You must have at least one of these scopes: 'unitgroups.delete, setup.manage'.")
    def UnitGroup_deleteById(id: str):
        '''Use this call to delete a unit group.<br>You must have at least one of these scopes: 'unitgroups.delete, setup.manage'.'''
        base_url = "https://api.apaleo.com"
        url = f"{base_url}/inventory/v1/unit-groups/{id}"
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e)
        access_token = os.getenv('OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if not access_token:
            raise ValueError('Missing OAuth2 access token in .env: OAUTH2_AUTHORIZATIONCODE_ACCESS_TOKEN')
        if id is None:
            raise ValueError('Missing required path parameter: id')
        headers['Authorization'] = f'Bearer {access_token}'
        try:
            resp = requests.delete(url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    mcp.run(transport="stdio")
